version: "3.8"

services:
  # Layanan Streamlit (Serving app)
  streamlit:
    container_name: streamlit_ml_app
    # Path Build
    build:
      context: ./Monitoring/inference
      dockerfile: Dockerfile
    image: water-potability-app:latest
    ports:
      - "8501:8501" # Streamlit UI
      - "8000:8000" # Prometheus Port
    restart: always
    # Memastikan server metrik di port 8000 sudah berjalan
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:8000/metrics || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # Layanan Prometheus (Pengumpul metrik)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_server
    ports:
      - "9090:9090"
    volumes:
      # Path volume
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    depends_on:
      streamlit:
        condition: service_healthy

  # Layanan Grafana (Visualisasi metrik)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafaran
    depends_on:
      - prometheus
  
volumes:
  grafana-storage:
  prometheus-storage: