global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "streamlit_app"
    metrics_path: /metrics
    static_configs:
      - targets: ["streamlit:8000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]